[package]
name = "vector-space-model"
version = "0.1.0"
edition = "2018"

[lib]
name = "vsm"
path = "src/vsm/mod.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
rust-stemmers = "1.2.0"
tokenizers = "0.11.0"